port:  5000
markdown: kramdown
name: Avenue Realty
title: Avenue Realty
url: http://Avenue.in/plots
description: "An interactive map that lets you find out how your building is zoned, learn where to locate your business and explore zoning patterns throughout Chicago."
encoding: utf-8
timezone: 	Asia/Kolkata
permalink: pretty
navigation:
- text: Home
  url: /
- text: Zoning districts
  url: /zones/
  category: zones
# - text: Zoning rules
#   url: /zoning_rules/
- text: About
  url: /about/